name: CI/CD Pipeline for TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove Existing Chrome (if any)
        run: |
          sudo apt purge -y google-chrome-stable || true
          sudo apt autoremove -y

      - name: Install Chrome (Specific Version 120)
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable=120.0.6099.199-1
          
          google-chrome --version

      - name: Install Matching ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR_VERSION=$(echo "$CHROME_VERSION" | cut -d'.' -f1)

          echo "Installed Chrome version: $CHROME_VERSION"
          echo "Chrome major version: $CHROME_MAJOR_VERSION"

          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")

          if [[ -z "$CHROMEDRIVER_VERSION" ]]; then
            echo "Error: No matching ChromeDriver found for Chrome version $CHROME_VERSION"
            exit 1
          fi

          echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver.zip

          if [[ ! -f "chromedriver.zip" ]]; then
            echo "Error: ChromeDriver download failed."
            exit 1
          fi

          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run Tests
        run: mvn clean test
