name: CI/CD Pipeline for TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          echo "Detected Chrome version: $CHROME_VERSION"

          if [ -z "$CHROME_VERSION" ]; then
            echo "Error: Unable to detect Chrome version."
            exit 1
          fi

          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Error: Unable to find a matching ChromeDriver version."
            exit 1
          fi

          echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"

          if [ ! -f "chromedriver_linux64.zip" ]; then
            echo "Error: ChromeDriver download failed."
            exit 1
          fi

          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run Tests
        run: mvn clean test
