name: CI/CD Pipeline for TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Stable Chrome Version
        run: |
          sudo apt update
          sudo apt remove -y google-chrome-stable || true  # Remove any existing version
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          # Get full Chrome version (e.g., 120.0.6099.199)
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
          echo "Full Chrome version: $CHROME_VERSION"

          # Get major version (e.g., 120)
          CHROME_MAJOR_VERSION=$(echo "$CHROME_VERSION" | cut -d'.' -f1)
          echo "Chrome major version: $CHROME_MAJOR_VERSION"

          # Fetch the correct ChromeDriver version
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")

          if [[ -z "$CHROMEDRIVER_VERSION" ]]; then
            echo "Error: No matching ChromeDriver found for Chrome version $CHROME_VERSION"
            exit 1
          fi

          echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"

          if [[ ! -f "chromedriver_linux64.zip" ]]; then
            echo "Error: ChromeDriver download failed."
            exit 1
          fi

          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run Tests
        run: mvn clean test
