name: Scheduled Runner

on:
  schedule:
    - cron: '*/1 * * * *'   # Runs daily at 4 PM UTC (9:30 PM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Java distribution
          java-version: '20'  # Set the Java version you use

      - name: Install Google Chrome
        run: |
          echo "Updating package lists..."
          sudo apt-get update
          echo "Installing Google Chrome..."
          sudo apt-get install -y google-chrome-stable
          echo "Google Chrome installed successfully."

      - name: Set up ChromeDriver
        run: |
          echo "Detecting installed Chrome version..."
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          echo "Installed Chrome major version: $CHROME_VERSION"
          
          echo "Fetching the latest compatible ChromeDriver version..."
          LATEST_RELEASE=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
          if [ -z "$LATEST_RELEASE" ]; then
            echo "Error: Could not fetch the latest ChromeDriver version."
            exit 1
          fi

          echo "Downloading ChromeDriver version: $LATEST_RELEASE..."
          curl -O "https://chromedriver.storage.googleapis.com/$LATEST_RELEASE/chromedriver_linux64.zip"
          
          echo "Extracting ChromeDriver..."
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          echo "ChromeDriver setup completed successfully."

      - name: Run Tests
        run: |
          echo "Starting test execution..."
          mvn test  # Adjust if using Gradle or a different test command
          echo "Test execution completed."
